/*
 * Generated by XDoclet - Do not edit!
 */
package be.businesstraining.ejb2;

/**
 * Local home interface for SommeDiviseurs.
 * @generated 
 * @wtp generated
 */
public interface SommeDiviseursLocalHome
   extends javax.ejb.EJBLocalHome
{
 
   public be.businesstraining.ejb2.SommeDiviseursLocal create()
      throws javax.ejb.CreateException;

}
