/*
 * Generated by XDoclet - Do not edit!
 */
package be.businesstraining.ejb2;

/**
 * Local interface for SommeDiviseurs.
 * @generated 
 * @wtp generated
 */
public interface SommeDiviseursLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public int sommeDiviseurs( int param ) ;

}
