/*
 * Generated by XDoclet - Do not edit!
 */
package be.businesstraining.beans;

/**
 * Remote interface for Calculette.
 * @generated 
 * @wtp generated
 */
public interface Calculette
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public int additionner( int a,int b )
      throws java.rmi.RemoteException;

}
