/*
 * Generated by XDoclet - Do not edit!
 */
package be.businesstraining.beans;

/**
 * Home interface for Calculette.
 * @generated 
 * @wtp generated
 */
public interface CalculetteHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Calculette";
   public static final String JNDI_NAME="Calculette";

   public be.businesstraining.beans.Calculette create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
