/*
 * Generated by XDoclet - Do not edit!
 */
package be.businesstraining.beans;

/**
 * Local interface for Calculette.
 * @generated 
 * @wtp generated
 */
public interface CalculetteLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public int additionner( int a,int b ) ;

}
