/*
 * Generated by XDoclet - Do not edit!
 */
package be.businesstraining.beans;

/**
 * Local home interface for Calculette.
 * @generated 
 * @wtp generated
 */
public interface CalculetteLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CalculetteLocal";
   public static final String JNDI_NAME="CalculetteLocal";

   public be.businesstraining.beans.CalculetteLocal create()
      throws javax.ejb.CreateException;

}
