/*
 * Generated by XDoclet - Do not edit!
 */
package be.businesstraining.ejb3;

/**
 * Home interface for EntiersParfaits.
 * @generated 
 * @wtp generated
 */
public interface EntiersParfaitsHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/EntiersParfaits";
   public static final String JNDI_NAME="EntiersParfaits";

   public be.businesstraining.ejb3.EntiersParfaits create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
