/*
 * Generated by XDoclet - Do not edit!
 */
package be.businesstraining.ejb3;

/**
 * Remote interface for EntiersParfaits.
 * @generated 
 * @wtp generated
 */
public interface EntiersParfaits
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public boolean estParfait( int param )
      throws java.rmi.RemoteException;

}
